{
 "title": "OpenStack Services Graphs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Instance", "query": "Prod, PreProd" }
  ]
 },
 "panels": [
  {
   "title": "OpenStack Services",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# OpenStack Services: ${Instance}\n\nGraphs of service availability"
   }
  },
  { "title": "Service Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "VM Creation (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /^$Instance$/ AND \"network\" != 'MonitoringPrivate') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VM Creation (Private)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /^$Instance$/ AND \"network\" = 'MonitoringPrivate') AND  $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Keystone",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"KeystoneBasic-create_tenant_with_users\" WHERE (\"instance\" =~  /^$Instance$/) AND  $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~  /^$Instance$/) AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Glance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"GlanceImages-create_and_list_image\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Nova",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NovaServers-list_servers\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Manila",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ManilaShares-create_share_and_access_from_vm",
     "query": "SELECT last(\"success\") FROM \"ManilaShares-create_share_and_access_from_vm\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Swift",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SwiftObjects-create_container_and_object_then_download_object",
     "query": "SELECT last(\"success\") FROM \"autogen\".\"SwiftObjects-create_container_and_object_then_download_object\" WHERE (\"instance\"::tag =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Octavia",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_list_loadbalancers",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"HeatStacks-create_and_list_stack\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  { "title": "OpenStack Component Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "VM Creation (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /^$Instance$/ AND \"network\" != 'MonitoringPrivate') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VM Creation (Private)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /^$Instance$/ AND \"network\" = 'MonitoringPrivate') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Keystone",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"KeystoneBasic-create_tenant_with_users\" WHERE (\"instance\" =~  /^$Instance$/) AND  $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~  /^$Instance$/) AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Glance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"GlanceImages-create_and_list_image\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Nova",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NovaServers-list_servers\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Cinder",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Manila",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"ManilaShares-create_share_and_access_from_vm\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Swift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_update_pools",
     "query": "SELECT last(\"success\") FROM \"autogen\".\"SwiftObjects-create_container_and_object_then_download_object\" WHERE (\"instance\"::tag =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Octavia",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_list_loadbalancers",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"HeatStacks-create_and_list_stack\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  { "title": "Results Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "VM Boot, Benchmark, Delete (Internal Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\", mean(\"nova-boot_server\") AS \"Create VM\", mean(\"nova-delete_server\") AS \"Delete VM\", mean(\"vm-run_command_over_ssh\") AS \"Run Command\", mean(\"vm-wait_for_ping\") AS \"Wait for Ping\", mean(\"vm-wait_for_ssh\") AS \"Wait for SSH\", mean(\"nova-get_console_output_server\") AS \"Get Console Output\" FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~ /^$Instance$/ AND \"network\" != 'MonitoringPrivate') AND $timeFilter GROUP BY time(5s) fill(null)"
    }
   ]
  },
  {
   "title": "VM Boot, Benchmark, Delete (Private Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\", mean(\"nova-boot_server\") AS \"Create VM\", mean(\"nova-delete_server\") AS \"Delete VM\", mean(\"vm-run_command_over_ssh\") AS \"Run Command\", mean(\"vm-wait_for_ping\") AS \"Wait for Ping\", mean(\"vm-wait_for_ssh\") AS \"Wait for SSH\", mean(\"nova-get_console_output_server\") AS \"Get Console Output\" FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~ /^$Instance$/ AND \"network\" = 'MonitoringPrivate') AND $timeFilter GROUP BY time(5s) fill(null)"
    }
   ]
  },
  {
   "title": "Identity - Create Project and Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\", mean(\"keystone_v3-create_project\") AS \" Create Project\", mean(\"keystone_v3-list_roles\") AS \"List Roles\", mean(\"keystone_v3-add_role\") AS \"Add Roles\", mean(\"keystone_v3-create_user\") AS \"Create User\", mean(\"keystone_v3-create_users\") AS \"Create Multiple Users\" FROM \"KeystoneBasic-create_tenant_with_users\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    }
   ]
  },
  {
   "title": "Neutron Create, List, and Delete Security Groups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\" FROM \"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NeutronSecurityGroup-create_and_delete_security_groups",
     "query": "SELECT mean(\"neutron-create_security_group\") AS \"Create Security Groups\" FROM \"autogen\".\"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "neutron-create_security_group" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NeutronSecurityGroup-create_and_delete_security_groups",
     "query": "SELECT mean(\"neutron-delete_security_group\") AS \"Delete Security Groups\" FROM \"autogen\".\"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "neutron-delete_security_group" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NeutronSecurityGroup-create_and_list_security_groups",
     "query": "SELECT mean(\"neutron-list_security_groups\") AS \"List Security Groups\" FROM \"autogen\".\"NeutronSecurityGroup-create_and_list_security_groups\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "neutron-list_security_groups" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Glance Create and List Image",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\", mean(\"glance-create_image\") AS \"Create Image\", mean(\"glance-list_images\") AS \"List Images\", mean(\"glance_v2-create_image\") AS \"V2 Create Image\", mean(\"glance_v2-list_images\") AS \"V2 List Images\" FROM \"GlanceImages-create_and_list_image\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    }
   ]
  },
  {
   "title": "Nova List Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\" FROM \"NovaServers-list_servers\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NovaServers-list_servers",
     "query": "SELECT mean(\"nova-list_servers\") AS \"List Servers\" FROM \"autogen\".\"NovaServers-list_servers\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nova-list_servers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cinder Create and Delete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\" FROM \"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT mean(\"cinder_v3-create_volume\") AS \"Create Volume\" FROM \"autogen\".\"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"cinder_v3-delete_volume\") AS \"Delete Volume\" FROM \"autogen\".\"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Manila Create and List Shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ManilaShares-create_share_and_access_from_vm",
     "query": "SELECT mean(\"duration\") AS \"Test Duration\" FROM \"autogen\".\"ManilaShares-create_share_and_access_from_vm\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ManilaShares-create_share_and_access_from_vm",
     "query": "SELECT mean(\"manila-create_share\") AS \"Create Share\" FROM \"autogen\".\"ManilaShares-create_share_and_access_from_vm\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "manila-create_share" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ManilaShares-list_shares",
     "select": [
      [
       { "params": [ "manila-list_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Swift Create Container, Upload and Download Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SwiftObjects-create_container_and_object_then_download_object",
     "query": "SELECT mean(\"duration\")AS \"Test Duration\" FROM \"autogen\".\"SwiftObjects-create_container_and_object_then_download_object\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SwiftObjects-create_container_and_object_then_download_object",
     "query": "SELECT mean(\"swift-create_container\") AS \"Create Container\" FROM \"autogen\".\"SwiftObjects-create_container_and_object_then_download_object\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "swift-create_container" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SwiftObjects-create_container_and_object_then_download_object",
     "query": "SELECT mean(\"swift-download_object\") AS  \"Download Object\" FROM \"autogen\".\"SwiftObjects-create_container_and_object_then_download_object\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "swift-download_object" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SwiftObjects-create_container_and_object_then_download_object",
     "query": "SELECT mean(\"swift-upload_object\") AS \"Upload Object\" FROM \"autogen\".\"SwiftObjects-create_container_and_object_then_download_object\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "swift-upload_object" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Octavia Create and List Loadbalancers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_list_loadbalancers",
     "query": "SELECT mean(\"duration\") AS \"Test Duration\" FROM \"autogen\".\"Octavia-create_and_list_loadbalancers\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_list_loadbalancers",
     "query": "SELECT mean(\"octavia-load_balancer_create\") AS \"Create Loadbalancer\" FROM \"autogen\".\"Octavia-create_and_list_loadbalancers\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octavia-load_balancer_create" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_list_loadbalancers",
     "query": "SELECT mean(\"octavia-load_balancer_list\")AS \"List Loadbalancers\" FROM \"autogen\".\"Octavia-create_and_list_loadbalancers\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octavia-load_balancer_list" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Octavia-create_and_list_loadbalancers",
     "query": "SELECT mean(\"octavia-wait_for_loadbalancers\") AS \"Wait for Loadbalancers\" FROM \"autogen\".\"Octavia-create_and_list_loadbalancers\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octavia-wait_for_loadbalancers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Heat Stack Create and List",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT mean(\"duration\") AS \"Test Duration\", mean(\"heat-create_stack\") AS \"Create Stack\", mean(\"heat-list_stacks\") AS \"List Stacks\" FROM \"HeatStacks-create_and_list_stack\" WHERE (\"instance\" =~ /^$Instance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    }
   ]
  }
 ]
}